### PR TITLE
Add Model3D Documentation to VBA-Docs/api

### PR DESCRIPTION
**Pull request by MattKeMS**

### CODE REVIEW

**Comment by Linda-Editor** [comment]
@MattKeMS Thanks, Matt. I'll take a look at this later today and will let you know if I need you to update anything before I merge it.

**Comment by Linda-Editor** [comment]
@MattKeMS Hi Matt - I need the object pages for the Model3DFormat topics (Excel.Model3DFormat.md, Word.Model3DFormat.md, etc.).

**Comment by MattKeMS** [comment]
@Linda-Editor , Thanks for the quick feedback Linda...I will provide those missing files tomorrow, along with a few others I neglected to commit.

 This was my first ever git pull request, so I will also celebrate this career milestone. :-)

**Comment by Linda-Editor** [comment]
@MattKeMS Thanks, Matt. For today, I will create stub topics for the Excel, Word, and PowerPoint pages to avoid publishing warnings. I'll let you know when they're ready and then you can edit as needed.

**Comment by Linda-Editor** [comment]
@MattKeMS Also, I'm going to wait a day or so, and then will add them to the TOC.

**Comment by Linda-Editor** [comment]
@MattKeMS I merged your latest changes; however, I'm still missing files for Shape.IncrementRotationZ.md and Shape.IncrementRotationY.md for Excel, PowerPoint, and Word.

**Comment by MattKeMS** [comment]
@Linda-Editor , Thanks Linda, I believe the links themselves are in error; they should refer instead to <app>.Model3DFormat.IncrementRotationZ.md, instead of <app>.Shape.IncrementRotationZ.md.  I can fix this tomorrow....but we don't need extra pages for those topics.

**Comment by Linda-Editor** [comment]
@MattKeMS No, that's okay. I can fix these since I'm in the repo now. Thanks for letting me know. :-)  Good work!

By the way, let me know if you're going to be doing more of these because there are some formatting best practices I'd like you to follow next time.

**Comment by Linda-Editor** [comment]
@MattKeMS Hey, I just found this other object, ThreeDFormat. https://docs.microsoft.com/en-us/office/vba/api/excel.threedformat

Is that different from the new topics? Please clarify, thanks.

**Comment by MattKeMS** [comment]
Hi @Linda-Editor, that is different (although I was an engineer on that project too, long ago).  The legacy 3D properties can be applied to standard shapes or text to make them draw as 3D.    The new Model3DFormat is for a much newer type of "3D Model" content, that lets customers insert pre-authored models into their documents, and exercise some configuration over them (e.g. rotate/crop/zoom).

**Comment by Linda-Editor** [comment]
@OfficeGlobal These are new Model3DFormat topics that have been added to VBA-Docs en-us. See the topics in the list above, which have been updated and errors fixed since this PR was created. To find all of them, filter on Model3DFormat. Sample object page: https://docs.microsoft.com/en-us/office/vba/api/excel.model3dformat. Also present in PowerPoint and Word. Let me know if you have any questions.

**Pull request merged**
