### PR TITLE
fix: Code fence languages

### PR DESCRIPTION
**Pull request by nschonni**
- Remove "text" values
- Updates some sql values to vb to match code inside blocks
- Update some sql blocks to ini files
- Add an IDL block that may not render currently
- remove inline triple backtick blocks

### CODE REVIEW

**Comment by Linda-Editor** [comment]
@nschonni Hi Nick, thanks for these updates; however, you cannot leave a code language blank (as you did when you removed "text") because it throws an error in our content quality reports. Can you either replace these with "text" or another code language that applies? After you do this, I'll merge this PR. Thanks.

**Comment by nschonni** [comment]
@Linda-Editor I replaced the explicit text code blocks with implicit code fences using indent. I think that should still pass your code metrics if you're using Markdownlint

**Comment by Linda-Editor** [comment]
@nschonni It just looks like you removed the code tags altogether. This is what I see: 
```text
VB /cmd cmdlineargs
```
changed to:
VB /cmd cmdlineargs

but it probably should be the following, right?
`VB /cmd cmdlineargs`

**Comment by nschonni** [comment]
If you indent the block, it creates a code block too. Without the triple backticks, I thought that would not trigger your code quality warning.
EX: you can see they still render as code blocks here https://github.com/MicrosoftDocs/VBA-Docs/blob/1ce3401ae59f18fa502dbcc2520ebe473be20971/Language/Reference/User-Interface-Help/command-function.md

**Comment by Linda-Editor** [comment]
@nschonni It appears to render in GitHub preview but I'm not sure if it will render in OPS (our publishing system) that way. You'd need to show me an example where that is live. Is there one? If not, I recommend using the single ticks to ensure that it renders properly.

**Comment by nschonni** [comment]
Sure, there are a bunch on the azure-docs repo. I'll see if I can dig one up for you

**Comment by nschonni** [comment]
Here is an example 
- source https://github.com/MicrosoftDocs/azure-docs/blob/f10653b10c2ad745f446b54a31664b7d9f9253fe/articles/data-lake-store/data-lake-store-get-started-net-sdk.md
- published https://docs.microsoft.com/en-ca/azure/data-lake-store/data-lake-store-get-started-net-sdk

**Comment by Linda-Editor** [comment]
@nschonni Thanks. Okay, I'll merge this and see what happens. Changes will be live later today.

**Pull request merged**
