### PR TITLE
Add SVG Graphic Style VBA documentation

### PR DESCRIPTION
**Pull request by RichardCory**

### CODE REVIEW

**Comment by Linda-Editor** [comment]
@RichardCory Thanks for these topics, Matt. I'll merge this PR tomorrow.

**Comment by RichardCory** [comment]
Looks like I've got a typo in TOC.md, but github won't show the file, because it's too big. On line 18173, there's an extra 'p' in PowerPoint.

###### [GraphicStyle](Power**p**Point.Shape.GraphicStyle.md)

Can you fix this during the merge?

**Comment by Linda-Editor** [comment]
Yep, I saw that. I'll fix it. :-)

**Comment by Linda-Editor** [comment]
@RichardCory I merged the changes and then edited the files. Note that I added the Example that was on the Word Shape page to the PowerPoint and Excel Shape pages. If you don't want that, let me know and I'll remove the instances on the latter two pages.

Changes will go live at the end of today. Let me know if you have any questions.

**Comment by Linda-Editor** [comment]
@OfficeGlobal These are new GraphicStyle topics that need to be added to loc versions. They include all the files above plus the following: word.shape.md and enumerations-office.md. Let me know if you have any questions. Here's a sample live link: https://docs.microsoft.com/en-us/office/vba/api/excel.shape.graphicstyle.

**Pull request merged**
