### PR TITLE
Improve *.Shapes.Add3DModel topics - fix code syntax and provide parameter names

### PR DESCRIPTION
**Pull request by MattKeMS**

### CODE REVIEW

**Comment by Linda-Editor** [comment]
@MattKeMS I merged these changes, and they'll be live later today.

**Comment by Linda-Editor** [comment]
@MattKeMS Changes are live, but I noticed these were not in the TOC yet or on the Shapes object pages, so I added them. Those changes will be live by EOD. Note that when I add "Add3DModel" to a list, I sort it as if it were "Add**Three**DModel."

**Comment by MattKeMS** [comment]
@Linda-Editor - Thank you for adding these to TOC, Linda.

I think I am finished with the Model3D documentation for now, but please let me know if I should change anything else, or add any more authorship/style rules to my new team wiki.

**Comment by Linda-Editor** [comment]
@MattKeMS Okay, Matt, will do.

**Pull request merged**
