### PR TITLE
Model3D API improvements - add missing object documentation files

### PR DESCRIPTION
**Pull request by MattKeMS**

### CODE REVIEW

**Comment by MattKeMS** [comment]
@Linda-Editor , Hi Linda, this contains the missing files for the new Model3D API documentation.

**Comment by Linda-Editor** [comment]
@MattKeMS I fixed all the broken links and added the topics to the TOC. I'm building to Master now, and if that comes out clean, I'll push to live (it takes about 1-2 hours for each build).

**Comment by Linda-Editor** [comment]
@MattKeMS All the topics are now live.
https://docs.microsoft.com/en-us/office/vba/api/excel.model3dformat

Apply "Model3D" in the Search filter above the left navigation to see all the new topics. Thanks for your contribution. I fixed all the broken links.

FOR FUTURE DOCUMENTATION:
1. Sentence-case all titles and headings (for example, "property" is lowercase, not capital.
2. For API links, no need to add the "./" before the file name.
3. For API topics, no need to add a See also; it's redundant with the Syntax link to the object
4. Bold the object link in the Syntax.
5. The usual order is Syntax, Parameters (if any), Return value, Example
6. You can also put the return value after "Read-only" or "Read/write". For example, "Read/write **String**.

**Comment by Linda-Editor** [comment]
@MattKeMS If you see variations in topics from what I described above, it's because I'm currently going through the entire repo making these updates. :-)

**Comment by MattKeMS** [comment]
Thank you, Linda!  I see the new pages are all online now.

Matt

**Comment by MattKeMS** [comment]
Thank you for the feedback, Linda.  I might not work on documentation much more myself in the immediate future, but my colleagues in Office Graphics will be working on a few other VBA areas soon (e.g. for SVG and Ink). I will add these notes to a team Wiki and share with my team.

Matt

**Comment by Linda-Editor** [comment]
@MattKeMS  Thanks, Matt. :-)

**Pull request merged**
