### PR TITLE
Adds a note about modern Office add-ins

### PR DESCRIPTION
**Pull request by mscharlock**
I work on the docs for Office Add-ins (https://github.com/OfficeDev/office-js-docs-pr) and by studying web analytics data, we think that adding a note to select high-trafficked pages of this docset will drive customers to a more modern add-ins solution, if they want that. Data from our customer surveys and interviews show that most people who have used previous versions of related Office technology do not discover the modern Office Add-in docs, so we are trying to drive discoverability. Happy to answer more questions on this if you have them.

### CODE REVIEW

**Comment by Linda-Editor** [comment]
@mscharlock I fixed the link for these. Based on the other include that we have, the link should contain a "~", not "../../../"

**Comment by mscharlock** [comment]
Ah awesome, very good to know - I always feel like I screw up the links in some way. Thanks!

**Comment by Linda-Editor** [comment]
@mscharlock No worries. VBA-Docs is a difficult repo for links because there are so many layers...

FYI: I just pushed all the changes live and they look great. Let me know if you have any questions.

**Comment by Linda-Editor** [comment]
If you do any more of these, here's the link to use (on any page): 
`[!include[Add-ins note](~/includes/addinsnote.md)]`

Please be sure to put it ABOVE the Support and Feedback include (which should be the last item on the page).

**Comment by lindalu-MSFT** [comment]
@Linda-Editor Thanks for fixing this! We sure miss you.

**Comment by lindalu-MSFT** [comment]
@mscharlock Do you need to fix this in the other repo?

**Comment by mscharlock** [comment]
@lindalu-MSFT I don't think so - I didn't get any warnings on the other one, so I assume they work.

**Pull request merged**
