### PR TITLE
chore: Remove old XML attributes on UL

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by Linda-Editor** [comment]
@nschonni These are broken tables. Your fixes did not fix them; I can take a look at these later. You need to realize that I'm going through this repo topic by topic to look for formatting issues like this, so next time you find a bunch of broken tables, just alert me, don't try and fix them. Thank you.

**Comment by nschonni** [comment]
I though the tables were OK, and that it was just left over XML attributes on the `<ul>` element inside cells on the table

**Comment by Linda-Editor** [comment]
@nschonni I've run into these before. The XML attributes are not needed, but the rest has to be formatted in such a way that the bulleted lists are inside the table; currently, they break the table and appear outside, even when you removed the XML attributes. But I know how to fix these. So if you run into them again, just file an Issue instead of a PR, and let me know which files you're seeing it in. Thanks.

**Comment by Linda-Editor** [comment]
I made these changes manually apart from this PR.

**Pull request closed without merging**
