### PR TITLE
Add boilerplate info about how to get support and provide feedback.

### PR DESCRIPTION
**Pull request by kbrandl**
Also, disable the OPS "feedback" feature. 

Note: this PR updates adds boilerplate to all files *except* for files in the `/api` folder (a separate PR will update those files).

### CODE REVIEW

**Comment by kbrandl** [comment]
@Linda-Editor here's the PR that adds the new boilerplate support/feedback content at the bottom of every file (and disables the OPS "feedback" feature). I've requested your review so that you can spot-check these changes. To do so, I'd suggest you take a look at the changes in several of the commits that this PR contains (for example: https://github.com/MicrosoftDocs/VBA-Docs/pull/680/commits/fed1c6ee7d4d59352bf727508313c39dc10c4e0e). 

image

The only type of change that you should see in each file is adding the `[!include[Support and feedback](~/includes/feedback-boilerplate.md)]` statement at the end of the file (sometimes extra blank lines are also added or removed near this statement -- but that's expected).

**Please do not merge this PR to master until you hear from me later today.** I'm waiting for the OPS build to finish so that I can verify that everything looks okay on the staging site.

**Comment by Linda-Editor** [comment]
@kbrandl Thanks, Kim, but where did you want me to check it? I can't access staging with my current perms (for 6 months I'm off corp-net). So the only place I can see these is in the GitHub UI, I think. Or I suppose I can clone GitHub and view your branch that way (in Visual Studio Code). Would that work?

**Comment by Linda-Editor** [comment]
@kbrandl I looked at the GitHub change file that you linked to above, and everything looks good on that.

**Comment by kbrandl** [comment]
@Linda-Editor you should use the GitHub UI to spot check the changes. 

1) Within this PR, click the **Commits** tab:
    image

2) From the **Commits** page, click the link for any of today's commits:

    image

3) Within each commit, the only type of change that you should see in each file is adding the `[!include[Support and feedback](~/includes/feedback-boilerplate.md)]` statement at the end of the file (sometimes extra blank lines are also added or removed near this statement -- but that's expected). 

Check several commits, and if you see any types of changes other than the new `[!include[Support and feedback](~/includes/feedback-boilerplate.md)]` statement (and blank lines added or removed) at the end of the file, let me know by commenting here.

**Comment by Linda-Editor** [comment]
@kbrandl Okay, will do.

**Comment by Linda-Editor** [comment]
@kbrandl I let Linda Lu know as soon as I saw that she did that, and she reverted the one PR she merged.

**Pull request merged**
