### PR TITLE
new files added

### PR DESCRIPTION
**Pull request by v-hearya**

### CODE REVIEW

**Comment by Linda-Editor** [comment]
@v-hearya I'll review this later today. Is there another file coming? Or is this it?

**Comment by v-hearya** [comment]
@Linda-Editor - Both files are added and TOC updated with new nodes.

**Comment by Linda-Editor** [comment]
@v-hearya Okay, I'm going to merge this to master, and then I'll do an edit pass on your submissions before pushing them live tomorrow.

**Comment by Linda-Editor** [comment]
@v-hearya Thanks for submitting these. Some tips for the next time: 1) don't use the old file name; look at the file names of similar topics and follow the pattern there (I updated these for you); 2) find the location in the TOC where other similar topics are located (I moved these for you); 3) look at other topics if possible to see how to use GitHub markdown to style tables (I redid these for you). The new file names are Visio.VisColoringMethod.md and Visio.VisRecordsetFieldStatus.md. Your changes will be live at the end of the day tomorrow.

**Comment by v-hearya** [comment]
@Linda-Editor - Thanks for your guidance and in future I'll keep these notes in mind.

**Comment by Linda-Editor** [comment]
@v-hearya These updates are now live; see https://docs.microsoft.com/en-us/office/vba/api/visio.viscoloringmethod and https://docs.microsoft.com/en-us/office/vba/api/visio.visrecordsetfieldstatus. Changes to the enumerations navigation page will go live later today.

**Pull request merged**
