### PR TITLE
Add documentation for properties and methods relating to Data Types.

### PR DESCRIPTION
**Pull request by astegmaier**
We are shipping the new [Data Types](https://support.office.com/en-us/article/stock-quotes-and-geographic-data-61a33056-9935-484f-8ac8-f1a89e210877) feature in Excel, and along with this, we've added some methods and properties that allow developers to create and interact with them.

### CODE REVIEW

**Comment by Linda-Editor** [comment]
@astegmaier Later today I'll add these to the TOC. Could you let me know where in the TOC you'd like them? https://docs.microsoft.com/en-us/office/vba/api/overview/excel

**Comment by astegmaier** [comment]
Most of the new articles should be under Excel > Object Model > Range, except for the new enum (XlLinkedDataTypeState), which should be under Excel > Object model.

For future reference, is there a file in the repo that controlls the table of contents? I can make sure to make that a part of future PRs.

**Comment by Linda-Editor** [comment]
@astegmaier Yes, there is a TOC file; however, it's huge, so it's safer if you just let us know where you want the files, and we can make the TOC updates. There are about 70,000 entries, and one glitch can break it. ;-)

I assume you want the enum file to be under Excel > Object Model > Enumerations? https://docs.microsoft.com/en-us/office/vba/api/excel(enumerations)

**Comment by Linda-Editor** [comment]
@astegmaier I updated the TOC and the corresponding navigation pages with the new topics.  Changes should be live by tomorrow. Thanks for contributing!

**Comment by Linda-Editor** [comment]
Your contribution is now live: https://docs.microsoft.com/en-us/office/vba/api/excel.range(object)

Let me know if you have any questions.

**Pull request merged**
