### PR TITLE
Fixing Markdown Syntax

### PR DESCRIPTION
**Pull request by robertmuehsig**
The whole site was a mess - hope i found everything.

### CODE REVIEW

**Comment by robertmuehsig** [comment]
Not really sure what failed, but the current site is really bugged right now.

**Comment by fenxu** [comment]
@robertmuehsig Investigating the root cause of this failure for this check.

**Comment by lindalu-MSFT** [comment]
Hi @robertmuehsig I ran a "Manual Publish" in the docs portal, can you verify if your changes went live or not?

**Comment by lindalu-MSFT** [comment]
By the way @robertmuehsig THANK YOU for this awesome PR. I'll do my best to get it merged. I really appreciate your help!

**Comment by robertmuehsig** [comment]
Hi @lindalu-MSFT - the site seems still broken: https://docs.microsoft.com/en-us/office/vba/outlook/how-to/navigation/best-practices-for-getting-and-setting-properties

**Comment by lindalu-MSFT** [comment]
Ack! @robertmuehsig I actually didn't finalize the merge! My bad. Your PR should be merged to live now, though it might take an hour or so to replicate as there are a few builds in the queue in front of it.

**Comment by robertmuehsig** [comment]
Much better now - thanks for merging @lindalu-MSFT !

**Pull request merged**
