### PR TITLE
updated range.find.md

### PR DESCRIPTION
**Pull request by jasonct05**

### CODE REVIEW

**Comment by Linda-Editor** [comment]
@jasonct05 Hi Jason, could you also update the following page and add the changes to this PR? https://docs.microsoft.com/en-us/office/vba/api/excel.xlfindlookin

Thanks...

**Comment by jasonct05** [comment]
Added description in excel.xlfindlookin

**Comment by Linda-Editor** [comment]
@jasonct05 Thanks. I merged this PR; changes will be live later today.

**Comment by jasonct05** [comment]
Thanks for the help Linda!

Best,
Jason Tan

On Jun 5, 2019, at 7:39 AM, Linda Caputo <notifications@github.com<mailto:notifications@github.com>> wrote:


@jasonct05<https://github.com/jasonct05> Thanks. I merged this PR; changes will be live later today.

**Pull request merged**
