### PR TITLE
Merge to live!

### PR DESCRIPTION
**Pull request by lindalu-MSFT**

### CODE REVIEW

**Comment by italicize** [comment]
@Linda-Editor I stumbled on the style sheet for VBA articles, [Document conventions (Visual Basic for Applications)](https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/document-conventions-visual-basic-for-applications). It agrees with the [Microsoft Writing Style Guide](https://docs.microsoft.com/en-us/style-guide/developer-content/formatting-developer-text-elements) about using bold and italic formatting for objects, properties, and other keywords.

Less monospace text is better for readers. The outline around monospace text is distracting, unlike the subtler emphasis of bold and italic formatting. An outline doesn't appear in GitHub but does at docs.microsoft.com, as rendered by Edge and Internet Explorer.

Thanks again to @Kagre, @lindalu-MSFT, @kbrandl, @Cloud-Writer, @Saisang, @JiayueHu, you, and everyone else working on the VBA reference.

(Later I'll add sample code to [Document conventions (Visual Basic for Applications)](https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/document-conventions-visual-basic-for-applications), which is missing.)

**Comment by Kagre** [comment]
@lindalu-MSFT, IMO the class md's really do need links to the methods, and properties like the other languages have.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequest?view=aspnetcore-2.1

**Comment by Kagre** [comment]
also from an editing via code perspective `**First Term** **Second Term**` is easier for the code to tell where the first term stops and the second starts than `**First Term Second Term**` is; the latter is far more likely to take human intervention when editing later on down the road.

**Comment by italicize** [comment]
@lindalu-MSFT I don't have templates, but I will look for some topics with good formatting. Also, may I ask, are the VBA articles stored in any way other than GitHub? Is GitHub the source or the product?

I agree with @Kagre about keeping the lists of properties and methods. It's faster to find and click a link in those lists than in the search and navigation pane on the left. The properties and methods could be bullet lists, instead of tables, to use less vertical space.

**Pull request merged**
